services:
  - type: web
    name: mktv5-render
    env: node
    plan: free
    region: oregon
    healthCheckPath: /api/health
    
    # Dependências do sistema para o Puppeteer (Chromium)
    build:
      apt:
        packages:
          - libnss3
          - libatk-bridge2.0-0
          - libcups2
          - libgtk-3-0
          - libxkbcommon0
          - libxss1
          - libasound2
          - libgbm1
          - chromium-browser
          
    buildCommand: "npm install && npm run build"
    startCommand: "npm run migrate:deploy && npm start"
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mktv5-render-db
          property: connectionString
      # ✅ CHAVE JWT ESSENCIAL ADICIONADA NOVAMENTE
      - key: JWT_SECRET
        generateValue: true
      # ✅ UPLOADS_DIR_NAME ADICIONADO NOVAMENTE
      - key: UPLOADS_DIR_NAME
        value: "uploads"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: GOOGLE_CLIENT_ID 
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false

    disks:
      - name: mktv5-uploads
        mountPath: /opt/render/project/src/uploads
        sizeGB: 1

databases:
  - name: mktv5-render-db
    plan: free
    databaseName: mktv5render
    user: mktv5renderuser
    region: oregon
